### PR TITLE
[WIP] Add finalists for 2017

### PR DESCRIPTION
**Pull request by allejo**
**Blocked by:** information/logos for rest of finalists

For now, they're only listed on the current contest page. Should they belong anywhere else or be moved elsewhere?

---

@thekaveman besides Twitter, are there any more social media icons that exist in this icon set? If not, could we some for the social media sites for the finalists? Current ones used by the finalists are:

- facebook
- twitter
- instagram
- google+

Don't know if you want to add all of them or only some of them? /cc @babadi

### CODE REVIEW

**Comment by thekaveman** [comment]
@allejo in that kit we have:

  - `social-facebook`
  - `social-google-plus`
  - `social-instagram`
  - `social-twitter`
  - `social-youtube`

**Comment by thekaveman** [comment]
> For now, they're only listed on the current contest page.

I think this is fine.

**Review by thekaveman — APPROVED** [review]
Looks good to me. Would organizing the finalists collection into subfolders by year (vs. having the year be part of the filename/yaml) make this any easier?

**Comment by allejo** [comment]
Moved the finalists into subfolders per year and moved the loop into its own template. We could add last HTB's finalists too if we want

**Comment by allejo** [comment]
Also, since this the grid is float based and each entry has different heights, that'll lead to problems with odd placements. Should we move it to a flex box based grid instead?

**Comment by thekaveman** [comment]
> Should we move it to a flex box based grid instead

I'm good with that, would be a nice improvement.

**Comment by thekaveman** [comment]
In fact, if you want to move to Bootstrap 4, that would be cool too... depends on how much time you want to spend 😉

**Comment by allejo** [comment]
I'm cool with moving to Bootstrap 4, I'll work on that 👍

**Comment by thekaveman** [comment]
For all intents and purposes, this site is offline. Thanks for the work over the years!

**Pull request closed without merging**
